import React,{useState,useEffect,useRef} from 'react';
import {Brand,Icon} from './Icons.jsx';
import {UserPill} from './Login.jsx';
const delay=s=>({'--reveal-delay':s+'s'});
export default function Landing({onStart,user,isAdmin,onOpenAdmin,onMyPage,onLogin,onLogout}){
 const [tab,setTab]=useState(0);
 const [menuOpen,setMenuOpen]=useState(false);
 const rootRef=useRef(null);
 useEffect(()=>{
  const els=rootRef.current.querySelectorAll('[data-reveal]');
  if(!('IntersectionObserver' in window)){els.forEach(el=>el.classList.add('is-visible'));return}
  const show=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.15,rootMargin:'0px 0px -8% 0px'});
  // Reset only once 80px past the viewport — beyond the 40–56px reveal offset — so it can't bounce back in and flicker.
  const reset=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)e.target.classList.remove('is-visible')}),{rootMargin:'80px 0px 80px 0px'});
  els.forEach(el=>{show.observe(el);reset.observe(el)});
  return()=>{show.disconnect();reset.disconnect()};
 },[]);
 return <div className="landing" ref={rootRef}><header className="site-nav"><div className="site-container nav-inner"><Brand onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}/><nav aria-label="주 메뉴"><a href="#how">서비스 소개</a><a href="#outputs">결과물 보기</a><a href="#faq">자주 묻는 질문</a></nav>{user?<div className="relative flex-shrink-0"><button aria-haspopup="menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)} className="flex items-center gap-1 rounded-full pr-1.5 hover:bg-[var(--muted)]"><UserPill user={user}/><Icon name="chevron" size={14} className={'text-[var(--muted-fg)] transition-transform duration-150 '+(menuOpen?'rotate-90':'')}/></button>{menuOpen&&<><div className="fixed inset-0 z-40" onClick={()=>setMenuOpen(false)} aria-hidden="true"/><div role="menu" className="absolute right-0 top-full mt-2 z-50 min-w-[132px] rounded-xl border border-[var(--border)] bg-white py-1 shadow-[0_12px_32px_-12px_rgba(15,23,42,.35)]">{isAdmin&&<button role="menuitem" onClick={()=>{setMenuOpen(false);onOpenAdmin()}} className="flex w-full items-center gap-2 whitespace-nowrap px-3 py-2 text-[13.5px] text-[var(--fg)] hover:bg-[var(--muted)]"><Icon name="grid" size={16}/>관리자 화면</button>}<button role="menuitem" onClick={()=>{setMenuOpen(false);onMyPage()}} className="flex w-full items-center gap-2 whitespace-nowrap px-3 py-2 text-[13.5px] text-[var(--fg)] hover:bg-[var(--muted)]"><Icon name="file" size={16}/>마이페이지</button><button role="menuitem" onClick={()=>{setMenuOpen(false);onLogout()}} className="flex w-full items-center gap-2 whitespace-nowrap px-3 py-2 text-[13.5px] text-[var(--fg)] hover:bg-[var(--muted)]"><Icon name="logout" size={16}/>로그아웃</button></div></>}</div>:<button className="flex-shrink-0 text-[13.5px] font-semibold text-[var(--muted-fg)] hover:text-[var(--fg)]" onClick={onLogin}>로그인</button>}<button className="btn small flex-shrink-0" onClick={onStart}>시작하기</button></div></header>
 <main><section className="hero site-container"><p className="hero-label" data-reveal="up">아이디어는 있는데 시작이 막막하다면</p><h1 data-reveal="up" style={delay(.08)}>지원사업 준비<br/><span>이제 한곳에서</span></h1><p className="hero-description" data-reveal="up" style={delay(.16)}>나에게 맞는 공고를 찾는 일부터<br/>사업계획서와 프로토타입을 준비하는 일까지.</p><button className="btn hero-cta" data-reveal="up" style={delay(.24)} onClick={onStart}>내 아이디어로 시작하기</button><div className="hero-summary" data-reveal="scale" style={delay(.4)} aria-label="지원사업 준비 과정"><div className="summary-input"><span className="service-symbol"><span>S</span></span><div><small>이런 아이디어를 준비하고 있어요</small><p>동네 운동시설을 쉽게 예약하는 서비스</p></div></div><div className="summary-results"><div data-reveal="up" style={delay(.6)}><span className="summary-number">01</span><span>맞는 공고 찾기</span><b>공고 3건</b></div><div data-reveal="up" style={delay(.7)}><span className="summary-number">02</span><span>계획서와 프로토타입</span><b>함께 준비</b></div><div data-reveal="up" style={delay(.8)}><span className="summary-number">03</span><span>제출 전 점검</span><b>빠짐없이</b></div></div><small className="sample-label">서비스 이용 과정 예시</small></div></section>
 <section className="intro-section" id="how"><div className="site-container"><h2 data-reveal="up">찾고 쓰고 확인하는 일<br/>따로 하지 않아도 괜찮아요</h2><p data-reveal="up" style={delay(.12)}>지원사업 준비에 필요한 과정을 연결했어요.<br/>지금 내게 필요한 일부터 차근차근 시작해 보세요.</p></div></section>
 <section className="service-section site-container"><div className="section-copy"><span className="section-label" data-reveal="up">맞춤 공고</span><h2 data-reveal="up" style={delay(.08)}>수많은 공고 중에서<br/>나에게 맞는 것만</h2><p data-reveal="up" style={delay(.16)}>아이템과 기업 정보를 알려주면<br/>신청할 수 있는 공고와 지원 조건을<br/>한눈에 확인할 수 있어요.</p><button className="text-link" data-reveal="up" style={delay(.24)} onClick={onStart}>맞는 공고 찾아보기 <Icon name="chevron" size={17}/></button></div><div className="notice-preview" data-reveal="right" style={delay(.1)}><div className="notice-preview-heading"><h3>이런 공고가 잘 맞아요</h3><span>예시</span></div>{[{title:'초기창업패키지',org:'창업진흥원',fit:92,amount:'최대 1억원'},{title:'예비창업패키지',org:'창업진흥원',fit:81,amount:'최대 5천만원'},{title:'스마트상점 기술보급',org:'중소벤처기업부',fit:68,amount:'최대 3천만원'}].map((x,i)=><div className="notice-preview-row" key={x.title} data-reveal="up" style={delay(.3+i*.12)}><span className={'notice-icon tone-'+i}><Icon name="file" size={23}/></span><div><h4>{x.title}</h4><p>{x.org} · {x.amount}</p></div><span className="fit-number">{x.fit}<small>%</small></span></div>)}</div></section>
 <section className="outputs-section" id="outputs"><div className="site-container service-section"><div className="document-preview" data-reveal="left"><div className="document-top"><span>S-Brain</span><span>초안</span></div><div className="document-title">{['사업계획서','프로토타입','검증 리포트'][tab]}</div>{tab===0?<><h3>동네의 운동을<br/>더 가깝게 만드는 방법</h3><div className="document-outline">{['문제 인식','실현 가능성','성장 전략','팀 구성'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><Icon name="check" size={17}/></div>)}</div></>:tab===1?<><h3>아이디어를<br/>직접 보여줄 수 있도록</h3><div className="product-preview"><b>로컬핏</b><h4>오늘은 어떤 운동을 할까요?</h4><div><span>피트니스</span><span>필라테스</span><span>요가</span></div><p>핵심 화면과 기능을 확인하는 프로토타입</p></div></>:<><h3>제출 전에<br/>한 번 더 꼼꼼하게</h3><div className="review-preview"><div><span>문서 구성</span><b>확인 완료</b></div><div><span>프로토타입 연결</span><b>확인 완료</b></div><div><span>시장 규모 출처</span><b className="warning-text">보완 필요</b></div></div><small>예시 결과이며 실제 심사 점수가 아니에요.</small></>}</div><div className="section-copy"><span className="section-label" data-reveal="up">계획부터 실행까지</span><h2 data-reveal="up" style={delay(.08)}>머릿속에 있던 생각을<br/>보여줄 수 있는 결과로</h2><p data-reveal="up" style={delay(.16)}>공고에 맞춘 사업계획서와<br/>아이디어를 설명할 프로토타입.<br/>서로 잘 맞는지도 함께 점검해요.</p><div className="output-tabs" role="tablist" aria-label="결과물 종류" data-reveal="up" style={delay(.24)}>{['사업계획서','프로토타입','검증 리포트'].map((x,i)=><button role="tab" aria-selected={tab===i} key={x} onClick={()=>setTab(i)} className={tab===i?'active':''}>{x}</button>)}</div></div></div></section>
 <section className="faq-section site-container" id="faq"><h2 data-reveal="up">궁금한 점이 있나요?</h2><div>{[['아이디어만 있어도 시작할 수 있나요?','네. 준비 중인 아이템과 신청자 정보를 입력하면 공고 매칭부터 시작할 수 있어요. 아직 창업 전이라면 예비창업자를 선택해 주세요.'],['만든 문서를 바로 제출해도 되나요?','사업계획서는 AI가 작성한 초안이에요. 사실 관계와 근거, 공고의 제출 양식을 직접 확인하고 수정한 뒤 제출해 주세요.'],['입력한 아이디어나 첨부한 자료는 안전하게 관리되나요?','네. 첨부한 원본 파일은 텍스트를 추출한 직후 바로 파기하고, 입력하신 정보는 회원 탈퇴 시 함께 삭제돼요. 학습 데이터 활용 동의는 선택 사항이라 언제든 껐다 켤 수 있어요.']].map(([q,a],i)=><details key={q} data-reveal="up" style={delay(.1+i*.1)}><summary>{q}<Icon name="plus" size={19}/></summary><p>{a}</p></details>)}</div></section>
 <section className="closing"><h2 data-reveal="up">생각만 해왔던 아이디어<br/>이제 시작해 볼까요?</h2><button className="btn" data-reveal="up" style={delay(.12)} onClick={onStart}>첫 프로젝트 만들기</button></section></main><footer className="site-footer"><Brand/><p>정부지원사업 준비를 더 쉽게</p><small>© 2026 S-Brain · 서비스 시연용 데모</small></footer></div>
}

// 로그인한 계정이 마이페이지를 저장(완료)하기 전까지, 마이페이지가 아닌 다른 화면으로
// 갈 때마다 이 위에 뜬다(App.jsx의 onboarded 게이트). 닫기·바깥 클릭이 전혀 없다 — 자기
// 정보를 저장하기 전까진 예외 없이 이 화면으로 돌아오게 하려는 것.
export function MyPageNudge({open,onGo}){
 if(!open)return null;
 return <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
  <div className="absolute inset-0 bg-[var(--fg)]/40 backdrop-blur-sm" aria-hidden="true"/>
  <div role="dialog" aria-modal="true" aria-labelledby="mypage-nudge-title" className="relative w-full max-w-lg rounded-3xl bg-white p-12 shadow-[0_24px_64px_-24px_rgba(15,23,42,.4)] text-center">
   <span className="inline-flex items-center justify-center w-20 h-20 rounded-2xl mb-6 bg-[var(--primary)]"><img src="/symbol-white.png" alt="" className="w-16 h-auto"/></span>
   <h2 id="mypage-nudge-title" className="font-extrabold text-[26px] leading-snug">내 정보를 입력하면<br/>더 좋은 공고매칭을 해드려요</h2>
   <p className="text-[16px] text-[var(--muted-fg)] mt-3 leading-relaxed">대표자 정보·사업자등록번호·보유 인증 같은 항목을 마이페이지에 미리 채워두면 자격 확인과 공고 추천이 더 정확해져요.</p>
   <button onClick={onGo} className="w-full mt-8 rounded-xl bg-[var(--primary)] text-white py-4 text-[16.5px] font-semibold hover:bg-[var(--primary-dim)] transition-[background-color,scale] duration-150 ease-out active:scale-[0.98]">마이페이지에서 정보 입력하기</button>
  </div>
 </div>;
}
