import React,{useEffect,useState} from 'react';
import {Icon} from './Icons.jsx';
export default function Preparation({kind='plan',onComplete,similarAnnouncements=[],compact=false}){
 const [stage,setStage]=useState(0);
 const [open,setOpen]=useState(null);
 const [reduce,setReduce]=useState(false);
 const descriptions={match:{title:'잘 맞는 공고를 찾고 있어요',done:'맞는 공고를 찾았어요',subtitle:'아이템과 신청 조건을 함께 살펴보고 있어요.',rows:['아이템의 지원 분야 확인','신청 가능한 공고 확인','추천할 공고 정리'],button:'매칭 결과 보기',object:'맞춤 공고'},plan:{title:'생각을 계획으로 옮기고 있어요',done:'사업계획서가 준비됐어요',subtitle:'선택한 공고의 작성 기준에 맞추고 있어요.',rows:['아이템과 공고 기준 연결','사업계획서·표·그래프 작성','내용과 근거 점검'],button:'계획서 확인하기',object:'사업계획서'},artifact:{title:'직접 보여줄 수 있게 만들어요',done:'프로토타입이 준비됐어요',subtitle:'사업계획서와 이어지는 결과물을 준비하고 있어요.',rows:compact?['핵심 내용 정리','인포그래픽 제작','결과물 확인']:['핵심 화면과 기능 구성','프로토타입·인포그래픽 제작','사업계획서와 결과물 확인'],button:'산출물 확인하기',object:compact?'인포그래픽':'프로토타입'}};
 const d=descriptions[kind];const done=stage>=3;const percent=[12,42,76,100][Math.min(stage,3)];
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;setReduce(reduced);if(reduced){setStage(3);return;}if(stage>=3)return;const t=setTimeout(()=>setStage(s=>s+1),1600);return()=>clearTimeout(t)},[stage]);
 useEffect(()=>{if(kind==='match'&&done){const t=setTimeout(onComplete,700);return()=>clearTimeout(t)}},[kind,done,onComplete]);
 return <section className={'preparation '+(done?'is-done':'')+(reduce?' reduced':'')}><div className="preparation-heading"><p>{d.object} 준비</p><h1>{done?d.done:d.title}</h1><span>{done?'준비된 내용을 확인해 주세요.':d.subtitle}</span></div><div className="preparation-stage"><div className="preparation-count" role="progressbar" aria-label={d.object+' 준비 진행률'} aria-valuenow={percent} aria-valuemin={0} aria-valuemax={100}>{done?<span className="preparation-done"><Icon name="check" size={45}/></span>:<><strong key={percent}>{percent}</strong><span>%</span></>}</div><div className="preparation-status" role="status" aria-live="polite">{done?'준비 완료':d.rows[stage]}</div><ol className="preparation-rows">{d.rows.map((row,i)=><li key={row} className={stage>i?'finished':stage===i?'working':''}><span className="preparation-row-icon">{stage>i?<Icon name="check" size={17}/>:<Icon name={kind==='match'?'search':kind==='plan'?'file':'code'} size={18}/>}</span><span>{row}</span><small>{stage>i?'완료':stage===i?'진행 중':'대기'}</small></li>)}</ol></div>{done?<button className="btn preparation-action" onClick={onComplete}>{d.button}</button>:<p className="preparation-caption">잠시만 기다려 주세요. 이 화면은 생성 과정을 보여주는 데모예요.</p>}{kind==='plan'&&<div className="preparation-related"><h2>함께 살펴볼 만한 공고</h2>{similarAnnouncements.map(a=><div className="related-item" key={a.title}><button aria-expanded={open===a.title} onClick={()=>setOpen(open===a.title?null:a.title)}><div><b>{a.title}</b><p>{a.org} · {a.amount}</p></div><Icon name="chevron" size={18}/></button>{open===a.title&&<p>{a.reason}</p>}</div>)}</div>}</section>
}
