import React,{useState} from 'react';
import {Brand,Icon} from './Icons.jsx';
import {NotificationBell,MY_PROJECTS,SIMILAR_ANNOUNCEMENT_ALERTS} from '../features/Workflow.jsx';
export const steps=[['intake','아이템 입력'],['match-results','공고 찾기'],['plan-form','사업계획서'],['artifact-result','프로토타입'],['final-verdict','제출 전 점검'],['review','최종 결과물']];
export function WorkspaceShell({view,user,onHome,onDashboard,onNewProject,onLogout,notifyEnabled,onToggleNotify,children}){
 const index=['match-progress','eligibility-gate','eligibility-fail'].includes(view)?1:view==='plan-progress'?2:view==='artifact-progress'?3:view==='final-pass'?4:steps.findIndex(x=>x[0]===view);
 return <div className={'workspace view-'+view}><header className="workspace-topbar"><div className="workspace-nav"><Brand onClick={onHome}/><button className={view==='dashboard'?'nav-active':''} onClick={onDashboard}>내 프로젝트</button><span className="nav-spacer"/><span className="demo-badge">체험 모드</span><NotificationBell alerts={SIMILAR_ANNOUNCEMENT_ALERTS} enabled={notifyEnabled} onToggle={onToggleNotify}/><button className="profile-button" onClick={onLogout}>{user?.name||'김창업'} 님</button></div></header>{index>=0&&<nav className="flow-navigation" aria-label="프로젝트 진행 단계"><ol>{steps.map(([key,label],i)=><li key={key} className={i===index?'current':i<index?'complete':''} aria-current={i===index?'step':undefined}><span>{i<index?<Icon name="check" size={13}/>:i+1}</span>{label}</li>)}</ol></nav>}<main className={'workflow-content '+(view==='dashboard'?'is-dashboard':'')} data-view={view} key={view}>{children}</main><footer className="workspace-footer"><span>S-Brain</span><p>체험용 예시 데이터예요. 실제 공고 조회·AI 생성·서버 저장은 연결되지 않았어요.</p></footer></div>
}
export function Dashboard({onNewProject,onOpenProject,notifyEnabled,alerts,isNewUser,onToggleNewUser}){
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('전체');const [guard,setGuard]=useState(false);
 const projects=isNewUser?[]:MY_PROJECTS;
 const filtered=projects.filter(p=>(p.name+' '+p.announcementTitle).includes(query)&&(filter==='전체'||(filter==='진행 중'?p.progress<100:p.progress===100)));
 const start=()=>{if(projects.some(p=>p.progress<100))setGuard(true);else onNewProject()};
 return <div className="dashboard"><div className="dashboard-heading"><div><p>내 프로젝트</p><h1>{isNewUser?'첫 아이디어를 들려주세요':'김창업 님, 이어서 준비해 볼까요?'}</h1></div><button className="btn" onClick={start}><Icon name="plus" size={19}/>새 프로젝트</button></div>{!isNewUser&&<button className="continue-card" onClick={()=>onOpenProject(MY_PROJECTS[0])}><span className="continue-icon"><Icon name="file" size={32}/></span><div><p>이어서 준비하기</p><h2>동네 헬스장 예약 서비스</h2><span>사업계획서를 작성하고 있어요</span></div><div className="continue-status"><span>6단계 중 3단계</span><b>계획서 확인하기 <Icon name="chevron" size={19}/></b></div></button>}{guard&&<div className="project-guard" role="status"><div><b>먼저 진행 중인 프로젝트를 확인해 주세요</b><p>한 번에 하나의 프로젝트를 준비할 수 있어요.</p></div><button className="btn small" onClick={()=>onOpenProject(MY_PROJECTS[0])}>이어서 준비하기</button><button className="btn btn-muted small" onClick={()=>{setGuard(false);onNewProject()}}>중단하고 새로 시작</button><button className="icon-button" aria-label="안내 닫기" onClick={()=>setGuard(false)}><Icon name="close"/></button></div>}
 {!isNewUser&&notifyEnabled&&<div className="match-notice"><span className="notice-mini"><Icon name="file" size={19}/></span><p>비슷한 아이템의 새 공고 <b>{alerts.length}건</b>이 있어요.</p><span>상단 알림에서 확인해 주세요</span></div>}
 <div className="projects-heading"><h2>전체 프로젝트 <span>{projects.length}</span></h2><label className="demo-toggle"><input type="checkbox" checked={isNewUser} onChange={e=>onToggleNewUser(e.target.checked)}/>신규 사용자 보기</label></div><div className="project-toolbar"><div className="filter-tabs" role="group" aria-label="프로젝트 상태">{['전체','진행 중','완료'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)} className={filter===f?'active':''}>{f}</button>)}</div>{!isNewUser&&<label className="project-search"><Icon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="프로젝트 검색" aria-label="프로젝트 검색"/></label>}</div>
 <div className="project-list">{filtered.map(p=><button className="project-row" key={p.id} onClick={()=>onOpenProject(p)}><span className={'project-symbol '+(p.progress===100?'done':'')}><Icon name={p.progress===100?'check':'folder'} size={26}/></span><div className="project-title"><h3>{p.name}</h3><p>{p.announcementTitle}<span>·</span>{p.updatedAt.replaceAll('-','.')} 수정</p></div><span className={'status-pill '+(p.progress===100?'done':'')}>{p.progress===100?'준비 완료':'계획서 작성 중'}</span><Icon name="chevron" size={21}/></button>)}{isNewUser?<div className="new-user"><span className="new-user-symbol"><Icon name="folder" size={45}/></span><h3>어떤 아이디어를 준비하고 있나요?</h3><p>아이템을 알려주시면 맞는 공고부터 찾아드릴게요.</p><button className="btn" onClick={onNewProject}>첫 프로젝트 만들기</button></div>:filtered.length===0?<div className="search-empty"><h3>검색 결과가 없어요</h3><p>다른 이름으로 검색해 보세요.</p><button className="btn btn-muted" onClick={()=>{setQuery('');setFilter('전체')}}>전체 보기</button></div>:null}</div><p className="workspace-note">작성한 문서는 초안이에요. 제출 전 공고 요건과 내용을 직접 확인해 주세요.</p></div>
}
