# -*- coding: utf-8 -*-
"""02_age_classifier.ipynb 를 만든다. 노트북을 손으로 고치지 말고 이 파일을 고친다."""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': list(lines)}


def code(*lines):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': list(lines)}


cells = [

md("# 02. 업력 문장 골라내기\n",
   "\n",
   "## 무엇을 하려는 건가\n",
   "\n",
   "공고문에는 이런 문장들이 섞여 있다.\n",
   "\n",
   "```\n",
   "\"창업 후 7년 이내 중소기업\"              ← 업력 조건이 맞다\n",
   "\"장기재직(3년 이상)이 필요한 근로자\"      ← 근속연수다. 업력이 아니다\n",
   "\"3개월 이상 영업 중인 소상공인\"           ← 개월이다. 년으로 읽으면 안 된다\n",
   "\"만 19세 ~ 만 45세\"                      ← 사람 나이다\n",
   "```\n",
   "\n",
   "**이 넷을 구분하는 것**이 목표다. 지금은 정규식 규칙이 하고 있는데,\n",
   "규칙은 모양이 조금만 달라지면 놓친다.\n",
   "\n",
   "여기서는 문장 332개를 보여주며 **기계가 스스로 구분법을 배우게** 한다.\n",
   "\n",
   "---\n",
   "\n",
   "## 먼저 알아둘 것 — 이 실험의 한계\n",
   "\n",
   "정답지를 사람이 아니라 **기존 규칙이 만들었다.** 그래서 이대로 점수를 재면\n",
   "\"규칙을 얼마나 잘 흉내 내나\"를 재는 것이지 \"규칙보다 나은가\"가 아니다.\n",
   "\n",
   "그래서 두 단계로 간다.\n",
   "\n",
   "| 단계 | 하는 일 | 알 수 있는 것 |\n",
   "| --- | --- | --- |\n",
   "| 1단계 | 규칙이 만든 정답지로 학습·채점 | 제대로 배웠는지 (점검용) |\n",
   "| 2단계 | 규칙과 모델의 **판단이 갈린 것만** 사람이 확인 | 누가 맞는지 (진짜 결론) |\n",
   "\n",
   "2단계가 핵심이다. 둘의 의견이 같은 건 볼 필요가 없고,\n",
   "**갈린 것만 보면 되니까 확인할 양이 확 줄어든다.**"),

code("# -*- coding: utf-8 -*-\n",
     "import io, os, sys, json, collections, random\n",
     "\n",
     "ROOT = os.path.abspath('..')\n",
     "if ROOT not in sys.path:\n",
     "    sys.path.insert(0, ROOT)\n",
     "\n",
     "DATA   = os.path.join(ROOT, 'ml', 'data')\n",
     "MODELS = os.path.join(ROOT, 'ml', 'models')\n",
     "os.makedirs(MODELS, exist_ok=True)\n",
     "\n",
     "LABELS = os.path.join(DATA, 'age_labels.jsonl')\n",
     "assert os.path.exists(LABELS), '01_dataset.ipynb 를 먼저 돌려야 한다'\n",
     "\n",
     "rows = [json.loads(l) for l in io.open(LABELS, encoding='utf-8') if l.strip()]\n",
     "print('문장 %d개' % len(rows))\n",
     "print('  업력 맞음 (1) :', sum(1 for r in rows if r['label'] == 1))\n",
     "print('  업력 아님 (0) :', sum(1 for r in rows if r['label'] == 0))"),

md("---\n",
   "\n",
   "## 1. 공부용과 시험용 나누기\n",
   "\n",
   "여기서도 똑같다. **공부한 문장으로 시험 보면 안 된다.**\n",
   "\n",
   "다만 이번엔 문장 하나가 곧 문제 하나라서, 앞 노트북처럼 복잡하게 묶을 필요가 없다.\n",
   "그냥 섞어서 자르되, **업력 맞음/아님 비율을 양쪽에 똑같이** 맞춘다.\n",
   "한쪽에 쏠리면 점수가 왜곡되기 때문이다.\n",
   "\n",
   "`SEED` 는 섞을 때 쓴 주사위 눈금이다. 적어두면 몇 번을 돌려도 같게 나뉜다."),

code("from sklearn.model_selection import train_test_split\n",
     "\n",
     "SEED = 20260916\n",
     "\n",
     "texts  = [r['quote'] for r in rows]\n",
     "labels = [r['label'] for r in rows]\n",
     "\n",
     "X_train, X_test, y_train, y_test, idx_train, idx_test = train_test_split(\n",
     "    texts, labels, range(len(rows)),\n",
     "    test_size=0.25,        # 4개 중 1개를 시험용으로\n",
     "    stratify=labels,       # 업력 맞음/아님 비율을 양쪽에 맞춘다\n",
     "    random_state=SEED,\n",
     ")\n",
     "\n",
     "print('공부용 %d개 (업력 %d · 아님 %d)' % (\n",
     "    len(X_train), sum(y_train), len(y_train) - sum(y_train)))\n",
     "print('시험용 %d개 (업력 %d · 아님 %d)' % (\n",
     "    len(X_test), sum(y_test), len(y_test) - sum(y_test)))"),

md("---\n",
   "\n",
   "## 2. 어떻게 가르치나\n",
   "\n",
   "두 단계다.\n",
   "\n",
   "**① 문장을 숫자로 바꾼다 (TF-IDF)**\n",
   "\n",
   "기계는 글자를 못 읽으니 숫자로 바꿔야 한다. 방법은 단순하다 —\n",
   "**글자 조각이 몇 번 나오는지 세는 것**이다.\n",
   "\n",
   "```\n",
   "\"창업 후 7년 이내\"  →  '창업'  '업 '  ' 후'  '7년'  '년 '  ' 이'  '이내' …\n",
   "```\n",
   "\n",
   "한국어는 띄어쓰기가 들쭉날쭉해서 단어로 자르면 놓치는 게 많다.\n",
   "그래서 **글자 2~4개씩 잘라서** 센다. '창업'과 '창업후'를 둘 다 잡을 수 있다.\n",
   "\n",
   "이름의 IDF 부분은 \"아무 문장에나 다 나오는 조각은 덜 중요하게 친다\"는 뜻이다.\n",
   "\n",
   "**② 선을 긋는다 (로지스틱 회귀)**\n",
   "\n",
   "숫자로 바뀐 문장들을 늘어놓고 **업력인 것과 아닌 것 사이에 선을 하나 긋는다.**\n",
   "새 문장이 오면 선의 어느 쪽에 떨어지는지 보고 판단한다.\n",
   "\n",
   "이게 전부다. 신경망도 GPU도 필요 없고 몇 초면 끝난다."),

code("from sklearn.feature_extraction.text import TfidfVectorizer\n",
     "from sklearn.linear_model import LogisticRegression\n",
     "from sklearn.pipeline import make_pipeline\n",
     "\n",
     "model = make_pipeline(\n",
     "    TfidfVectorizer(\n",
     "        analyzer='char_wb',      # 글자 단위로 자른다 (한국어에 유리)\n",
     "        ngram_range=(2, 4),      # 2~4글자씩\n",
     "        min_df=2,                # 딱 한 번만 나온 조각은 버린다 (우연일 가능성)\n",
     "        sublinear_tf=True,\n",
     "    ),\n",
     "    LogisticRegression(\n",
     "        max_iter=2000,\n",
     "        class_weight='balanced', # 업력 아님이 더 많으므로 균형을 맞춘다\n",
     "        C=1.0,\n",
     "    ),\n",
     ")\n",
     "\n",
     "model.fit(X_train, y_train)\n",
     "print('학습 끝')"),

md("---\n",
   "\n",
   "## 3. 시험 — 얼마나 맞히나\n",
   "\n",
   "점수를 볼 때 **정확도 하나만 보면 안 된다.** 업력 아님이 더 많아서,\n",
   "전부 \"업력 아님\"이라고만 찍어도 정확도가 61%나 나오기 때문이다.\n",
   "\n",
   "그래서 두 가지를 같이 본다.\n",
   "\n",
   "| 이름 | 뜻 | 낮으면 생기는 일 |\n",
   "| --- | --- | --- |\n",
   "| **정밀도** | 업력이라고 한 것 중 진짜 업력인 비율 | 엉뚱한 걸 업력으로 읽어 **잘못된 자격 판정** |\n",
   "| **재현율** | 진짜 업력 중 찾아낸 비율 | 업력을 놓쳐서 **판정을 못 함** |\n",
   "\n",
   "이 프로젝트에서는 **정밀도가 더 중요하다.** 놓치는 건 \"확인 필요\"로 남기면 되지만,\n",
   "잘못 읽으면 사용자에게 틀린 자격 판정을 보여주게 된다."),

code("from sklearn.metrics import classification_report, confusion_matrix\n",
     "\n",
     "pred = model.predict(X_test)\n",
     "\n",
     "print(classification_report(\n",
     "    y_test, pred,\n",
     "    target_names=['업력 아님(0)', '업력 맞음(1)'],\n",
     "    digits=3, zero_division=0))"),

code("import numpy as np\n",
     "cm = confusion_matrix(y_test, pred)\n",
     "\n",
     "print('                    모델 판단')\n",
     "print('                업력아님   업력맞음')\n",
     "print('실제 업력아님      %4d      %4d' % (cm[0][0], cm[0][1]))\n",
     "print('실제 업력맞음      %4d      %4d' % (cm[1][0], cm[1][1]))\n",
     "print()\n",
     "print('대각선(%d, %d)이 맞힌 것이다.' % (cm[0][0], cm[1][1]))\n",
     "print('오른쪽 위 %d개 = 업력이 아닌데 업력이라고 했다  ← 이게 제일 위험하다' % cm[0][1])\n",
     "print('왼쪽 아래 %d개 = 업력인데 놓쳤다' % cm[1][0])"),

md("### 틀린 것을 눈으로 본다\n",
   "\n",
   "숫자만 보면 왜 틀렸는지 모른다. 실제 문장을 봐야 고칠 방향이 보인다."),

code("proba = model.predict_proba(X_test)[:, 1]   # 업력일 확률\n",
     "\n",
     "wrong = [(X_test[i], y_test[i], pred[i], proba[i])\n",
     "         for i in range(len(X_test)) if y_test[i] != pred[i]]\n",
     "\n",
     "print('틀린 것 %d개\\n' % len(wrong))\n",
     "for text, truth, got, p in sorted(wrong, key=lambda x: -abs(x[3] - 0.5))[:12]:\n",
     "    mark = '업력 아닌데 업력이라 함' if truth == 0 else '업력인데 놓침'\n",
     "    print('[%s · 확신 %.0f%%]' % (mark, max(p, 1 - p) * 100))\n",
     "    print('   ', text[:80])\n",
     "    print()"),

md("---\n",
   "\n",
   "## 4. 애매하면 판단하지 않는다\n",
   "\n",
   "이 프로젝트의 원칙은 **\"모르는 것과 아닌 것은 다르다\"** 이다.\n",
   "`gate.py` 가 통과·미달·**확인 필요** 세 값을 쓰는 것도 같은 이유다.\n",
   "\n",
   "모델도 똑같이 만든다. 확률이 애매한 구간(예: 35~65%)은\n",
   "0도 1도 아닌 **\"모르겠음\"** 으로 빼낸다.\n",
   "\n",
   "그러면 판단하는 건수는 줄지만, **판단한 것의 정확도는 올라간다.**\n",
   "아래에서 그 맞바꿈이 실제로 얼마나 되는지 본다."),

code("def with_abstain(low, high):\n",
     "    \"\"\"확률이 low~high 사이면 판단을 보류한다.\"\"\"\n",
     "    judged = [(t, p) for t, p in zip(y_test, proba) if not (low <= p <= high)]\n",
     "    if not judged:\n",
     "        return 0, 0.0\n",
     "    ok = sum(1 for t, p in judged if t == (1 if p > high else 0))\n",
     "    return len(judged), ok / len(judged)\n",
     "\n",
     "print('%-16s %-12s %s' % ('보류 구간', '판단한 건수', '판단한 것의 정확도'))\n",
     "print('-' * 52)\n",
     "for low, high in ((0.5, 0.5), (0.4, 0.6), (0.35, 0.65), (0.3, 0.7), (0.25, 0.75)):\n",
     "    n, acc = with_abstain(low, high)\n",
     "    label = '없음(전부 판단)' if low == high else '%.2f ~ %.2f' % (low, high)\n",
     "    print('%-16s %-12s %.1f%%' % (label, '%d / %d' % (n, len(y_test)), acc * 100))"),

md("---\n",
   "\n",
   "## 5. 진짜 시험 — 규칙과 모델이 갈린 것\n",
   "\n",
   "여기부터가 핵심이다.\n",
   "\n",
   "지금까지 잰 점수는 **규칙이 만든 정답지 기준**이라, 잘 나와봐야\n",
   "\"규칙을 잘 흉내 냈다\"는 뜻이다. 규칙보다 나은지는 아직 모른다.\n",
   "\n",
   "**둘의 판단이 갈린 문장만 뽑아서 사람이 보면 된다.**\n",
   "같은 판단을 한 건 볼 필요가 없으니, 확인할 양이 크게 줄어든다.\n",
   "\n",
   "아래 칸이 그 목록을 파일로 뽑는다."),

code("# 전체 332개에 대해 모델 판단을 구하고, 규칙(=기존 라벨)과 갈린 것만 모은다.\n",
     "all_proba = model.predict_proba(texts)[:, 1]\n",
     "\n",
     "disagree = []\n",
     "for i, r in enumerate(rows):\n",
     "    rule = r['label']\n",
     "    mine = 1 if all_proba[i] > 0.5 else 0\n",
     "    if rule != mine:\n",
     "        disagree.append({\n",
     "            'notice_id': r['notice_id'],\n",
     "            'quote': r['quote'],\n",
     "            'rule_says': rule,\n",
     "            'model_says': mine,\n",
     "            'model_confidence': round(float(max(all_proba[i], 1 - all_proba[i])), 3),\n",
     "            'human': None,        # ← 사람이 채울 칸. 1 = 업력 / 0 = 아님\n",
     "        })\n",
     "\n",
     "disagree.sort(key=lambda d: -d['model_confidence'])\n",
     "\n",
     "out = os.path.join(DATA, 'age_disagreements.jsonl')\n",
     "with io.open(out, 'w', encoding='utf-8') as f:\n",
     "    for d in disagree:\n",
     "        f.write(json.dumps(d, ensure_ascii=False) + '\\n')\n",
     "\n",
     "print('전체 %d개 중 판단이 갈린 것 %d개 (%.1f%%)'\n",
     "      % (len(rows), len(disagree), len(disagree) / len(rows) * 100))\n",
     "print('→', out)\n",
     "print()\n",
     "print('이 파일의 human 칸을 채우면 규칙과 모델 중 누가 맞았는지 알 수 있다.')"),

code("# 갈린 것 중 모델이 특히 확신하는 것부터 본다. 여기에 규칙의 허점이 드러난다.\n",
     "for d in disagree[:15]:\n",
     "    print('규칙:%s  모델:%s (확신 %.0f%%)' % (\n",
     "        '업력' if d['rule_says'] else '아님',\n",
     "        '업력' if d['model_says'] else '아님',\n",
     "        d['model_confidence'] * 100))\n",
     "    print('   ', d['quote'][:80])\n",
     "    print()"),

md("---\n",
   "\n",
   "## 6. 모델 저장\n",
   "\n",
   "제출물이 되는 파일이다. 몇 백 KB 정도라 git 에 올려도 된다."),

code("import joblib\n",
     "\n",
     "path = os.path.join(MODELS, 'age_classifier_v1.joblib')\n",
     "joblib.dump(model, path)\n",
     "print('저장 →', path)\n",
     "print('크기 : %.1f KB' % (os.path.getsize(path) / 1024))\n",
     "\n",
     "# 잘 불러와지는지 확인\n",
     "loaded = joblib.load(path)\n",
     "for s in ['창업 후 5년 이내 중소기업',\n",
     "          '장기재직 3년 이상 근로자',\n",
     "          '만 20세 이상 39세 이하',\n",
     "          '6개월 이상 영업 중인 소상공인']:\n",
     "    p = loaded.predict_proba([s])[0][1]\n",
     "    print('  %-32s → 업력일 확률 %.0f%%' % (s, p * 100))"),

md("---\n",
   "\n",
   "## 정리\n",
   "\n",
   "만들어진 것\n",
   "\n",
   "- `ml/models/age_classifier_v1.joblib` — 학습한 모델 (제출물)\n",
   "- `ml/data/age_disagreements.jsonl` — 규칙과 갈린 목록 (사람 확인용)\n",
   "\n",
   "**다음에 할 일**\n",
   "\n",
   "`age_disagreements.jsonl` 의 `human` 칸을 채운다. 1 = 업력 / 0 = 아님.\n",
   "다 채울 필요는 없고 위에서부터 100개 정도면 충분하다.\n",
   "\n",
   "그걸로 이런 표를 만들 수 있고, 이게 결과서의 결론이 된다.\n",
   "\n",
   "| | 규칙이 맞음 | 모델이 맞음 |\n",
   "| --- | --- | --- |\n",
   "| 갈린 100건 중 | ?건 | ?건 |\n",
   "\n",
   "모델이 더 많이 맞으면 규칙을 교체할 근거가 되고,\n",
   "규칙이 더 많이 맞으면 **\"학습해봤으나 규칙이 나아서 쓰지 않기로 했다\"** 가 된다.\n",
   "**어느 쪽이든 결과서에 쓸 수 있는 결론이다.** 실험은 좋게 나와야만 가치가 있는 게 아니다."),
]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.11'},
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

out = os.path.join(HERE, '02_age_classifier.ipynb')
with io.open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('만들었다 →', out, '· 셀 %d개' % len(cells))
