# -*- coding: utf-8 -*-
"""01_dataset.ipynb 를 만든다. 노트북을 손으로 편집하는 대신 이 파일을 고친다."""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': list(lines)}


def code(*lines):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': list(lines)}


cells = [

md("# 01. 학습 데이터 준비\n",
   "\n",
   "ML/DL 학습에 쓸 라벨을 모으고, **학습/시험 분할을 여기서 한 번 고정**한다.\n",
   "\n",
   "이 노트북이 만드는 것\n",
   "\n",
   "| 파일 | 내용 |\n",
   "|---|---|\n",
   "| `eval/splits.json` | 질의 60건의 학습/시험 분할. **한 번 정하면 바꾸지 않는다** |\n",
   "| `ml/data/age_labels.jsonl` | 업력 근거 문장 라벨 (P2 분류기용) |\n",
   "\n",
   "---\n",
   "\n",
   "**실행 전 준비**\n",
   "\n",
   "1. `data-collection/.env` 가 있어야 한다 (EC2 MySQL 접속). git 에 없으므로 직접 복사한다.\n",
   "2. `pip install -r requirements-ml.txt`\n",
   "3. GPU 를 쓰려면 torch 를 CUDA 판으로 따로 깐다 (아래 칸에서 확인)"),

code("# -*- coding: utf-8 -*-\n",
     "import os, sys, json, collections, random\n",
     "\n",
     "# 이 노트북은 data-collection/ml/ 에서 돈다. 상위 폴더를 import 경로에 넣는다.\n",
     "ROOT = os.path.abspath('..')\n",
     "if ROOT not in sys.path:\n",
     "    sys.path.insert(0, ROOT)\n",
     "\n",
     "EVAL = os.path.join(ROOT, 'eval')\n",
     "OUT  = os.path.join(ROOT, 'ml', 'data')\n",
     "os.makedirs(OUT, exist_ok=True)\n",
     "\n",
     "print('저장소 :', ROOT)\n",
     "print('.env   :', '있음' if os.path.exists(os.path.join(ROOT, '.env')) else '없음 ← 복사해야 한다')"),

code("# GPU 확인. False 가 나오면 torch 가 CPU 판이라 학습이 매우 느려진다.\n",
     "try:\n",
     "    import torch\n",
     "    print('torch', torch.__version__)\n",
     "    if torch.cuda.is_available():\n",
     "        name = torch.cuda.get_device_name(0)\n",
     "        vram = torch.cuda.get_device_properties(0).total_memory / 1024**3\n",
     "        print('CUDA 사용 가능 :', name, '· VRAM %.1fGB' % vram)\n",
     "    else:\n",
     "        print('CUDA 사용 불가 — CPU 판이다. 아래로 다시 설치한다.')\n",
     "        print('  pip uninstall -y torch')\n",
     "        print('  pip install torch --index-url https://download.pytorch.org/whl/cu124')\n",
     "except ImportError:\n",
     "    print('torch 가 없다. P2(고전 ML)만 하려면 없어도 된다.')"),

md("---\n",
   "\n",
   "## 1. 검색 관련도 라벨 — 무엇이 있나\n",
   "\n",
   "`eval/qrels.jsonl` 이 곧 학습 데이터다. 새로 만들 필요가 없다.\n",
   "\n",
   "- `topic_rel` **2** 딱 맞음 / **1** 분야는 걸치나 핵심 다름 / **0** 무관\n",
   "- `judge` 가 `human` 이면 사람 판정, `llm_old` 면 LLM 판정"),

code("def read_jsonl(path):\n",
     "    with io.open(path, encoding='utf-8') as f:\n",
     "        return [json.loads(l) for l in f if l.strip()]\n",
     "\n",
     "import io\n",
     "queries = read_jsonl(os.path.join(EVAL, 'queries.jsonl'))\n",
     "qrels   = read_jsonl(os.path.join(EVAL, 'qrels.jsonl'))\n",
     "\n",
     "print('질의 %d건 · 판정 %d쌍' % (len(queries), len(qrels)))\n",
     "print()\n",
     "print('관련도 분포 :', dict(sorted(collections.Counter(r['topic_rel'] for r in qrels).items())))\n",
     "print('판정자 분포 :', dict(collections.Counter(r['judge'] for r in qrels)))\n",
     "print('질의 종류   :', dict(collections.Counter(q['kind'] for q in queries)))"),

md("### 분야(category)는 층화 기준으로 쓸 수 없다\n",
   "\n",
   "분야가 너무 잘게 나뉘어 있어서, 대부분 1~3건뿐이다.\n",
   "1건짜리 분야는 학습/시험 어느 쪽에 넣어도 한쪽이 비게 된다.\n",
   "\n",
   "그래서 **층화는 `kind`(정상/무관)로만 하고, 분야는 나눈 뒤 분포를 확인만 한다.**"),

code("cat = collections.Counter(q['category'] for q in queries)\n",
     "print('분야 %d종 / 질의 %d건' % (len(cat), len(queries)))\n",
     "print()\n",
     "for name, n in cat.most_common():\n",
     "    print('  %-14s %d' % (name, n))"),

md("---\n",
   "\n",
   "## 2. 왜 질의 단위로 나눠야 하나 — 데이터 누수\n",
   "\n",
   "「사람 판정을 시험용, LLM 판정을 학습용」으로 나누고 싶어지지만 **그러면 안 된다.**\n",
   "\n",
   "사람 판정이 특정 질의에 몰려 있는 게 아니라 **여러 질의에 흩어져** 있기 때문이다.\n",
   "같은 질의가 학습과 시험 양쪽에 걸치면, 모델이 시험 문제를 미리 본 셈이 되어\n",
   "성능이 실제보다 높게 나온다. 그렇게 나온 숫자는 결과서에 쓸 수 없다.\n",
   "\n",
   "아래에서 실제로 그런지 확인한다."),

code("by_q = collections.defaultdict(collections.Counter)\n",
     "for r in qrels:\n",
     "    by_q[r['qid']][r['judge']] += 1\n",
     "\n",
     "has_human = [q for q, c in by_q.items() if c['human']]\n",
     "has_both  = [q for q, c in by_q.items() if c['human'] and (c['llm_old'] or c['llm'])]\n",
     "\n",
     "print('판정이 있는 질의        : %d건' % len(by_q))\n",
     "print('사람 판정이 있는 질의    : %d건' % len(has_human))\n",
     "print('사람+LLM 이 섞인 질의    : %d건  ← 이만큼이 누수 위험' % len(has_both))\n",
     "print()\n",
     "print('판정자로 나누면 %d개 질의가 학습·시험 양쪽에 걸친다.' % len(has_both))\n",
     "print('그래서 질의 단위로 나눈다.')"),

md("---\n",
   "\n",
   "## 3. 학습/시험 분할 고정\n",
   "\n",
   "**기준**\n",
   "\n",
   "- 질의 단위로 나눈다 (한 질의의 판정은 전부 같은 쪽으로 간다)\n",
   "- `kind` 로 층화한다 — 정상 질의와 무관 질의의 비율을 양쪽에서 맞춘다\n",
   "- 학습 40 : 시험 20 (2:1)\n",
   "- `SEED` 를 고정해 몇 번을 돌려도 같은 분할이 나오게 한다\n",
   "\n",
   "⚠ **이 분할은 한 번 정하면 바꾸지 않는다.** 바꾸면 그 전에 낸 성능 수치가 전부 무의미해진다.\n",
   "이미 `splits.json` 이 있으면 덮어쓰지 않고 그대로 읽는다."),

code("SEED = 20260916\n",
     "TEST_RATIO = 1/3          # 60건 중 20건을 시험용으로\n",
     "SPLITS = os.path.join(EVAL, 'splits.json')\n",
     "\n",
     "if os.path.exists(SPLITS):\n",
     "    splits = json.load(io.open(SPLITS, encoding='utf-8'))\n",
     "    print('이미 있다. 그대로 쓴다 →', SPLITS)\n",
     "else:\n",
     "    rng = random.Random(SEED)\n",
     "    train, test = [], []\n",
     "    # kind 별로 따로 섞어 같은 비율로 자른다 (층화)\n",
     "    for kind in ('normal', 'negative'):\n",
     "        group = sorted(q['qid'] for q in queries if q['kind'] == kind)\n",
     "        rng.shuffle(group)\n",
     "        cut = round(len(group) * TEST_RATIO)\n",
     "        test += group[:cut]\n",
     "        train += group[cut:]\n",
     "    splits = {\n",
     "        'seed': SEED,\n",
     "        'stratify': ['kind'],\n",
     "        'note': 'category 는 종류가 26개라 대부분 1~3건뿐이어서 층화 기준으로 쓰지 않았다.',\n",
     "        'train': sorted(train),\n",
     "        'test': sorted(test),\n",
     "    }\n",
     "    with io.open(SPLITS, 'w', encoding='utf-8') as f:\n",
     "        json.dump(splits, f, ensure_ascii=False, indent=1)\n",
     "    print('새로 만들었다 →', SPLITS)\n",
     "\n",
     "print('학습 %d질의 · 시험 %d질의' % (len(splits['train']), len(splits['test'])))"),

code("# 분할 검증 — 겹치는 질의가 없는지, 쌍이 몇 개씩 가는지, 분야가 한쪽에 쏠리지 않는지\n",
     "tr, te = set(splits['train']), set(splits['test'])\n",
     "assert not (tr & te), '학습과 시험에 같은 질의가 있다'\n",
     "assert len(tr | te) == len(queries), '빠진 질의가 있다'\n",
     "print('겹침 없음 · 빠짐 없음')\n",
     "print()\n",
     "\n",
     "kind_of = {q['qid']: q['kind'] for q in queries}\n",
     "cat_of  = {q['qid']: q['category'] for q in queries}\n",
     "\n",
     "for name, group in (('학습', tr), ('시험', te)):\n",
     "    pairs = sum(1 for r in qrels if r['qid'] in group)\n",
     "    human = sum(1 for r in qrels if r['qid'] in group and r['judge'] == 'human')\n",
     "    kinds = collections.Counter(kind_of[q] for q in group)\n",
     "    print('%s : 질의 %2d · 판정쌍 %4d (사람 %3d) · 정상 %d / 무관 %d'\n",
     "          % (name, len(group), pairs, human, kinds['normal'], kinds['negative']))\n",
     "\n",
     "print()\n",
     "print('분야 쏠림 확인 (학습에만 있거나 시험에만 있는 분야)')\n",
     "tr_cat = set(cat_of[q] for q in tr)\n",
     "te_cat = set(cat_of[q] for q in te)\n",
     "print('  시험에만 있는 분야 :', sorted(te_cat - tr_cat))\n",
     "print('  → 이 분야들은 학습 때 본 적 없는 분야다. 성능이 낮게 나와도 정상이다.')"),

md("---\n",
   "\n",
   "## 4. 업력 근거 문장 라벨 (P2 분류기용)\n",
   "\n",
   "LLM 이 공고문에서 업력 조건을 뽑을 때 **근거 문장(`age_source_quote`)** 을 같이 남긴다.\n",
   "그 값이 규칙 검산을 통과했는지로 라벨을 만든다.\n",
   "\n",
   "```\n",
   "근거 문장이 있다\n",
   "  ├ age_years_max 값이 남았다   → 라벨 1 : 진짜 업력 조건\n",
   "  ├ no_age_limit 표시가 있다    → 라벨 1 : 업력 제한 없음 (업력 얘기는 맞다)\n",
   "  └ 값이 비었다                → 라벨 0 : 업력이 아닌 것 (사람 나이·근속·개월)\n",
   "```\n",
   "\n",
   "즉 **추가 라벨링 없이 학습 데이터가 나온다.** 다만 이건 사람이 아니라 규칙이 만든\n",
   "**약한 라벨**이므로, 나중에 일부를 사람이 검수해 정확도를 확인해야 한다."),

code("# EC2 MySQL 에서 근거 문장을 읽는다. .env 가 있어야 한다.\n",
     "import store_mysql\n",
     "\n",
     "conn = store_mysql.connect()\n",
     "cur = conn.cursor()\n",
     "cur.execute('''\n",
     "    SELECT notice_id, age_source_quote, age_years_max, age_years_min, no_age_limit\n",
     "      FROM notice_conditions\n",
     "     WHERE age_source_quote IS NOT NULL AND age_source_quote <> ''\n",
     "''')\n",
     "rows = cur.fetchall()\n",
     "print('근거 문장이 있는 공고 %d건' % len(rows))"),

code("labels = []\n",
     "for notice_id, quote, ymax, ymin, no_limit in rows:\n",
     "    is_age = 1 if (ymax is not None or ymin is not None or no_limit) else 0\n",
     "    labels.append({\n",
     "        'notice_id': notice_id,\n",
     "        'quote': ' '.join(str(quote).split()),   # 연속 공백 정리\n",
     "        'label': is_age,                          # 1 = 업력 조건 / 0 = 업력 아님\n",
     "        'age_years_max': ymax,\n",
     "        'age_years_min': ymin,\n",
     "        'no_age_limit': int(bool(no_limit)),\n",
     "    })\n",
     "\n",
     "path = os.path.join(OUT, 'age_labels.jsonl')\n",
     "with io.open(path, 'w', encoding='utf-8') as f:\n",
     "    for r in labels:\n",
     "        f.write(json.dumps(r, ensure_ascii=False) + '\\n')\n",
     "\n",
     "dist = collections.Counter(r['label'] for r in labels)\n",
     "print('저장 →', path)\n",
     "print('라벨 1 (업력 조건)   : %d건' % dist[1])\n",
     "print('라벨 0 (업력 아님)   : %d건' % dist[0])\n",
     "print('합계                : %d건' % len(labels))"),

code("# 실제로 어떻게 생겼는지 눈으로 본다. 라벨이 말이 되는지 확인하는 단계다.\n",
     "for target, title in ((1, '라벨 1 — 진짜 업력 조건'), (0, '라벨 0 — 업력이 아닌 것')):\n",
     "    print('=' * 70)\n",
     "    print(title)\n",
     "    print('=' * 70)\n",
     "    shown = [r for r in labels if r['label'] == target][:8]\n",
     "    for r in shown:\n",
     "        print('  %-60s' % r['quote'][:60])\n",
     "    print()"),

md("---\n",
   "\n",
   "## 정리\n",
   "\n",
   "만들어진 것\n",
   "\n",
   "- `eval/splits.json` — 학습/시험 분할. **이후 모든 실험이 이 분할을 쓴다**\n",
   "- `ml/data/age_labels.jsonl` — 업력 근거 문장 라벨\n",
   "\n",
   "다음 단계\n",
   "\n",
   "| 노트북 | 내용 |\n",
   "|---|---|\n",
   "| `02_age_classifier.ipynb` | P2 — 근거 문장 분류기 (고전 ML). 반나절 |\n",
   "| `03_reranker_train.py` | P1 — 리랭커 파인튜닝 (딥러닝). GPU |\n",
   "| `04_reranker_report.ipynb` | P1 평가·비교표 |\n",
   "\n",
   "**평가는 `eval/evaluate.py` 를 그대로 호출한다.** 노트북에서 지표를 새로 구현하면\n",
   "기존 베이스라인(dense 0.494 / RRF 0.577)과 비교가 되지 않는다."),
]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.11'},
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

out = os.path.join(HERE, '01_dataset.ipynb')
with io.open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('만들었다 →', out, '· 셀 %d개' % len(cells))
