# -*- coding: utf-8 -*-
"""05_reranker_report.ipynb 를 만든다. 노트북을 손으로 고치지 말고 이 파일을 고친다."""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': list(lines)}


def code(*lines):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': list(lines)}


cells = [

md("# 05. 리랭커 성능 측정\n",
   "\n",
   "## 무엇을 재는 건가\n",
   "\n",
   "검색은 지금 이렇게 돈다.\n",
   "\n",
   "```\n",
   "공고 2,153건 ──[빠른 검색]──▶ 상위 30건 ──▶ 상위 3건을 화면에\n",
   "```\n",
   "\n",
   "여기에 리랭커를 끼우면 이렇게 된다.\n",
   "\n",
   "```\n",
   "공고 2,153건 ──[빠른 검색]──▶ 30건 ──[리랭커가 다시 읽고 순서 바꿈]──▶ 상위 3건\n",
   "```\n",
   "\n",
   "**뒤쪽에 밀려 있던 좋은 공고를 위로 끌어올리는 것**이 목적이다.\n",
   "그게 실제로 되는지 숫자로 확인한다.\n",
   "\n",
   "## 무엇끼리 비교하나\n",
   "\n",
   "| 이름 | 설명 |\n",
   "| --- | --- |\n",
   "| `dense` | 지금 서비스가 쓰는 방식 (의미 검색만) |\n",
   "| `rrf` | 의미 검색 + 단어 검색을 섞은 것 |\n",
   "| `rrf+rerank` (사전학습) | 남이 만든 리랭커를 그대로 얹은 것 |\n",
   "| `rrf+rerank` (학습) | **우리가 가르친 리랭커**를 얹은 것 |\n",
   "\n",
   "세 번째와 네 번째를 비교해야 **\"가르친 게 효과가 있었나\"** 를 알 수 있다.\n",
   "\n",
   "## 시험 문제는 20개만 쓴다\n",
   "\n",
   "60개 중 40개는 리랭커를 가르칠 때 썼다. 그걸로 시험 보면 의미가 없으므로\n",
   "**한 번도 안 보여준 20개로만** 잰다.\n",
   "\n",
   "---\n",
   "\n",
   "## 실행 전 준비\n",
   "\n",
   "1. `04_reranker_train.py` 를 먼저 돌려 모델을 만든다\n",
   "2. 벡터 색인이 이 PC 에 있어야 한다 (아래 칸이 확인·생성한다)"),

code("# -*- coding: utf-8 -*-\n",
     "import io, os, sys, json, time, collections\n",
     "\n",
     "ROOT = os.path.abspath('..')\n",
     "if os.path.basename(os.getcwd()) == 'ml':\n",
     "    os.chdir(ROOT)\n",
     "\n",
     "# 모델을 아직 안 받았다면 내려받아야 하므로 오프라인 모드를 끈다.\n",
     "# (vecstore.py 가 HF_HUB_OFFLINE 을 1 로 기본 설정하는데, 미리 0 을 넣어 막는다)\n",
     "os.environ.setdefault('HF_HUB_OFFLINE', '0')\n",
     "\n",
     "sys.path[:0] = [ROOT, os.path.join(ROOT, 'eval'), os.path.join(ROOT, 'ml')]\n",
     "\n",
     "import rerank_common as rc\n",
     "print('작업 폴더 :', os.getcwd())\n",
     "print('학습한 모델 :', '있음' if os.path.exists(rc.ADAPTER_DIR) else '없음 ← 04 를 먼저 돌린다')"),

md("### 벡터 색인 확인\n",
   "\n",
   "리랭커에 넣을 후보 30건을 뽑으려면 기존 검색이 돌아야 한다.\n",
   "검색은 벡터 색인(Chroma)을 쓰는데, 이 파일은 git 에 올리지 않으므로\n",
   "**이 PC 에서 한 번 만들어야** 한다. EC2 DB 의 벡터를 그대로 옮기는 것이라\n",
   "몇 초면 끝난다."),

code("import chromadb\n",
     "\n",
     "store = os.path.join(ROOT, 'data', 'vecstore', 'chroma')\n",
     "need = True\n",
     "if os.path.exists(store):\n",
     "    try:\n",
     "        col = chromadb.PersistentClient(path=store).get_collection('notices_v1')\n",
     "        print('색인 있음 · %d건' % col.count())\n",
     "        need = col.count() < 100\n",
     "    except Exception as e:\n",
     "        print('색인을 열지 못했다:', e)\n",
     "\n",
     "if need:\n",
     "    print('색인을 만든다 (EC2 DB 의 벡터를 옮긴다)...')\n",
     "    import ec2_vecstore\n",
     "    ec2_vecstore.run(rebuild=True)\n",
     "    print('완료')"),

md("---\n",
   "\n",
   "## 1. 시험 문제 20개 준비"),

code("import common\n",
     "import evaluate as ev\n",
     "\n",
     "splits = rc.load_splits()\n",
     "all_queries = common.load_queries()\n",
     "test_queries = {qid: all_queries[qid] for qid in splits['test'] if qid in all_queries}\n",
     "\n",
     "qrels = rc.load_qrels()\n",
     "\n",
     "kinds = collections.Counter(q['kind'] for q in test_queries.values())\n",
     "print('시험 질의 %d개 (정상 %d · 무관 %d)'\n",
     "      % (len(test_queries), kinds['normal'], kinds['negative']))\n",
     "print('학습에 쓴 질의 %d개는 여기에 없다.' % len(splits['train']))"),

md("### 공고 문장을 미리 다 받아둔다\n",
   "\n",
   "리랭커는 후보 30건의 **본문**을 읽어야 한다. 이걸 질의가 올 때마다 DB 에서\n",
   "가져오면 접속을 수십 번 하게 되고, 원격 DB 라 중간에 끊긴다.\n",
   "\n",
   "그래서 **여기서 한 번에 다 받아 메모리에 올려둔다.** 2,153건이라 몇 MB 뿐이다.\n",
   "이 뒤로는 DB 를 건드리지 않는다."),

code("t0 = time.time()\n",
     "all_notices = common.load_notices(None, with_attachment=False)\n",
     "NOTICE_TEXTS = {nid: rc.notice_text(n) for nid, n in all_notices.items()}\n",
     "del all_notices\n",
     "\n",
     "sample = next(iter(NOTICE_TEXTS.values()))\n",
     "print('공고 %d건 · %.1f초' % (len(NOTICE_TEXTS), time.time() - t0))\n",
     "print('평균 길이 %d자' % (sum(len(t) for t in NOTICE_TEXTS.values()) // len(NOTICE_TEXTS)))\n",
     "print()\n",
     "print('리랭커가 읽는 문장은 이렇게 생겼다:')\n",
     "print(' ', sample[:200], '...')"),

md("---\n",
   "\n",
   "## 2. 리랭커를 기존 평가 코드에 끼우기\n",
   "\n",
   "**지표를 새로 만들지 않는다.** `eval/evaluate.py` 가 이미 Recall@3 · nDCG@3 를\n",
   "계산하고 있고, 기존 성적(dense 0.494 / rrf 0.577)도 그 코드로 나온 값이다.\n",
   "여기서 다시 구현하면 숫자를 비교할 수 없게 된다.\n",
   "\n",
   "그래서 기존 `Systems` 를 물려받아 **`+rerank` 라는 이름만 추가**한다.\n",
   "나머지 동작은 손대지 않는다."),

code("class RerankSystems(ev.Systems):\n",
     "    \"\"\"기존 검색에 리랭커 한 단계를 덧붙인다.\n",
     "\n",
     "    'rrf+rerank' 처럼 이름 뒤에 +rerank 를 붙이면,\n",
     "    원래 방식으로 후보 POOL 건을 뽑은 뒤 리랭커가 순서를 다시 매긴다.\n",
     "    \"\"\"\n",
     "\n",
     "    POOL = 30      # 리랭커가 다시 읽을 후보 수\n",
     "\n",
     "    def __init__(self, scorer, texts):\n",
     "        super().__init__()\n",
     "        self.scorer = scorer\n",
     "        self.texts = texts        # 미리 받아둔 {공고id: 문장}. DB 를 다시 안 본다\n",
     "        self.elapsed = []\n",
     "\n",
     "    def run(self, name, q, k=30):\n",
     "        if not name.endswith('+rerank'):\n",
     "            return super().run(name, q, k)\n",
     "        base = name[:-len('+rerank')]\n",
     "        hits = super().run(base, q, k=self.POOL)\n",
     "        ids = [n for n, _ in hits]\n",
     "        if not ids:\n",
     "            return []\n",
     "        t0 = time.time()\n",
     "        texts = [self.texts.get(i, '') for i in ids]\n",
     "        scores = self.scorer.score(common.query_text(q), texts)\n",
     "        self.elapsed.append((time.time() - t0) * 1000)\n",
     "        return sorted(zip(ids, scores), key=lambda x: -x[1])[:k]\n",
     "\n",
     "print('준비됨. 후보 %d건을 다시 읽는다.' % RerankSystems.POOL)"),

md("---\n",
   "\n",
   "## 3. 기준선 — 리랭커 없이\n",
   "\n",
   "먼저 지금 방식의 성적을 시험 20문제로 잰다. 이게 비교 대상이다.\n",
   "\n",
   "**지표 읽는 법**\n",
   "\n",
   "| 이름 | 뜻 |\n",
   "| --- | --- |\n",
   "| `P@3(2)` | 화면에 보이는 3건 중 \"딱 맞음\" 비율. **주 지표** |\n",
   "| `nDCG@3` | 좋은 것이 위쪽에 있을수록 높다 |\n",
   "| `미판정@3` | 3건 중 정답지에 없는 것의 비율. 높으면 점수를 못 믿는다 |"),

code("results = []\n",
     "\n",
     "def measure(label, system_name, systems):\n",
     "    per = ev.evaluate(system_name, test_queries, qrels, systems)\n",
     "    s = ev.summarize(label, per)\n",
     "    s['_per'] = per\n",
     "    results.append(s)\n",
     "    print('%-26s P@3(≥1) %.3f · P@3(2) %.3f · nDCG@3 %.3f · 미판정 %.3f'\n",
     "          % (label, s['p3_rel'], s['p3_rec'], s['ndcg3'], s['unjudged3']))\n",
     "    return s\n",
     "\n",
     "plain = ev.Systems()\n",
     "measure('dense (현재 서비스)', 'dense', plain)\n",
     "measure('rrf (의미+단어)', 'rrf', plain)"),

md("---\n",
   "\n",
   "## 4. 사전학습 리랭커 — 가르치기 전\n",
   "\n",
   "남이 만들어 둔 리랭커를 그대로 얹는다. **우리 데이터로 가르치지 않은 상태**다.\n",
   "\n",
   "처음 실행하면 모델을 내려받는다(약 2.2GB). 한 번만 받으면 다음부터는 빠르다."),

code("t0 = time.time()\n",
     "base_scorer = rc.Scorer()                   # adapter 없음 = 사전학습 그대로\n",
     "print('모델 준비 %.0f초 · 장치 %s' % (time.time() - t0, base_scorer.device))\n",
     "\n",
     "base_sys = RerankSystems(base_scorer, NOTICE_TEXTS)\n",
     "measure('rrf+rerank (사전학습)', 'rrf+rerank', base_sys)\n",
     "print('질의당 리랭킹 시간 : 평균 %.0f ms' % (sum(base_sys.elapsed) / len(base_sys.elapsed)))"),

md("---\n",
   "\n",
   "## 5. 우리가 가르친 리랭커\n",
   "\n",
   "`04_reranker_train.py` 가 만든 모델을 얹는다. 위와 **후보도 같고 조건도 같다.**\n",
   "다른 건 리랭커가 우리 데이터를 배웠다는 것뿐이다."),

code("tuned_scorer = rc.Scorer(adapter=rc.ADAPTER_DIR)\n",
     "tuned_sys = RerankSystems(tuned_scorer, NOTICE_TEXTS)\n",
     "measure('rrf+rerank (학습)', 'rrf+rerank', tuned_sys)\n",
     "print('질의당 리랭킹 시간 : 평균 %.0f ms' % (sum(tuned_sys.elapsed) / len(tuned_sys.elapsed)))"),

md("---\n",
   "\n",
   "## 6. 결과 한눈에"),

code("print('%-26s %-10s %-10s %-10s %-10s %-9s'\n",
     "      % ('시스템', 'P@3(≥1)', 'P@3(2)', '판정칸만', 'nDCG@3', '미판정@3'))\n",
     "print('-' * 86)\n",
     "for s in results:\n",
     "    judged = s['p3_rec_judged']\n",
     "    print('%-26s %-10.3f %-10.3f %-10s %-10.3f %-9.3f'\n",
     "          % (s['system'], s['p3_rel'], s['p3_rec'],\n",
     "             '%.3f' % judged if judged is not None else '  -  ',\n",
     "             s['ndcg3'], s['unjudged3']))\n",
     "\n",
     "print()\n",
     "print('P@3(≥1)  주 지표. 「관련 있음」 기준 — 사람·LLM 판정 일치율 0.80 구간이다.')\n",
     "print('P@3(2)   참고. 「딱 맞음」 기준 — 일치율 0.64 로 기준 미달이라 단독으로 읽지 않는다.')\n",
     "print('미판정@3 0.10 을 넘으면 그 줄의 숫자를 믿지 않는다 (evaluate.py 원칙).')"),

md("### 차이가 진짜인지 확인\n",
   "\n",
   "질의가 20개뿐이라 **점수가 조금 올라간 것은 우연일 수 있다.**\n",
   "그래서 질의별로 짝지어 비교하고 95% 구간을 본다.\n",
   "\n",
   "**구간이 0 을 걸치면 \"좋아졌다고 말할 수 없다\"** 는 뜻이다.\n",
   "이걸 확인하지 않고 \"올랐습니다\"라고 쓰면 안 된다."),

code("base = results[1]      # rrf 를 기준으로 삼는다\n",
     "\n",
     "for metric, title in (('p3_rel', 'P@3(≥1) — 주 지표'), ('p3_rec', 'P@3(2) — 참고')):\n",
     "    print('== %s ==   기준 : %s' % (title, base['system']))\n",
     "    for s in results:\n",
     "        if s is base:\n",
     "            continue\n",
     "        d = ev.paired_diff([r[metric] for r in base['_per'] if r['kind'] == 'normal'],\n",
     "                           [r[metric] for r in s['_per'] if r['kind'] == 'normal'])\n",
     "        if not d:\n",
     "            continue\n",
     "        mid, lo, hi = d\n",
     "        verdict = ('개선이라 볼 수 있다' if lo > 0 else\n",
     "                   '나빠졌다' if hi < 0 else '차이를 단정할 수 없다')\n",
     "        print('  %-26s %+.3f  (%+.3f ~ %+.3f)   → %s' % (s['system'], mid, lo, hi, verdict))\n",
     "    print()"),

md("---\n",
   "\n",
   "## 7. 학습 과정 그림\n",
   "\n",
   "손실(loss)은 **틀린 정도**다. 낮을수록 좋다.\n",
   "\n",
   "- 학습 손실만 내려가고 시험 손실이 올라가면 → **외워버린 것**(과적합)\n",
   "- 둘 다 내려가면 → 제대로 배운 것"),

code("import matplotlib\n",
     "matplotlib.rcParams['font.family'] = 'Malgun Gothic'\n",
     "matplotlib.rcParams['axes.unicode_minus'] = False\n",
     "import matplotlib.pyplot as plt\n",
     "\n",
     "info = json.load(io.open(os.path.join(rc.ADAPTER_DIR, 'train_info.json'), encoding='utf-8'))\n",
     "h = info['history']\n",
     "\n",
     "fig, ax = plt.subplots(figsize=(6, 3.6))\n",
     "ax.plot([r['epoch'] for r in h], [r['train_loss'] for r in h], marker='o', label='학습 손실')\n",
     "ax.plot([r['epoch'] for r in h], [r['test_loss'] for r in h], marker='s', label='시험 손실')\n",
     "ax.set_xlabel('바퀴(epoch)'); ax.set_ylabel('손실'); ax.legend(); ax.grid(alpha=.3)\n",
     "ax.set_title('리랭커 학습 곡선')\n",
     "fig.tight_layout()\n",
     "fig.savefig(os.path.join(ROOT, 'ml', 'data', 'reranker_loss.png'), dpi=150)\n",
     "plt.show()\n",
     "\n",
     "print('학습 설정 :', {k: info[k] for k in ('epochs', 'effective_batch', 'lr', 'lora_rank')})\n",
     "print('학습한 부품 : %s개 / 전체 %s개 (%.2f%%)'\n",
     "      % (f\"{info['trainable_params']:,}\", f\"{info['total_params']:,}\",\n",
     "         info['trainable_params'] / info['total_params'] * 100))"),

md("---\n",
   "\n",
   "## 8. 문서에 넣을 숫자\n",
   "\n",
   "「학습한 ML/DL 모델」 문서의 **3.1 저장·추론** 표에 그대로 들어갈 값들이다."),

code("def dir_size(path):\n",
     "    total = 0\n",
     "    for root, _, files in os.walk(path):\n",
     "        for f in files:\n",
     "            total += os.path.getsize(os.path.join(root, f))\n",
     "    return total\n",
     "\n",
     "adapter_mb = dir_size(rc.ADAPTER_DIR) / 1024**2\n",
     "clf = os.path.join(ROOT, 'ml', 'models', 'age_classifier_v1.joblib')\n",
     "\n",
     "rows = [\n",
     "    ('업력 분류기 크기', '%.1f' % (os.path.getsize(clf) / 1024) if os.path.exists(clf) else '-', 'KB'),\n",
     "    ('리랭커 LoRA 크기', '%.1f' % adapter_mb, 'MB'),\n",
     "    ('리랭커 후보 수', str(RerankSystems.POOL), '건'),\n",
     "    ('리랭킹 시간 (GPU)', '%.0f' % (sum(tuned_sys.elapsed) / len(tuned_sys.elapsed)), 'ms/질의'),\n",
     "]\n",
     "for name, value, unit in rows:\n",
     "    print('%-22s %10s %s' % (name, value, unit))\n",
     "\n",
     "if tuned_scorer.device == 'cuda':\n",
     "    import torch\n",
     "    print('%-22s %10.1f GB' % ('GPU 최대 사용량', torch.cuda.max_memory_allocated() / 1024**3))"),

md("---\n",
   "\n",
   "## 9. 결과 저장\n",
   "\n",
   "문서를 쓸 때 다시 돌리지 않아도 되도록 파일로 남긴다."),

code("out = os.path.join(ROOT, 'ml', 'data', 'reranker_results.json')\n",
     "json.dump({\n",
     "    'test_queries': len(test_queries),\n",
     "    'pool': RerankSystems.POOL,\n",
     "    'train_info': info,\n",
     "    'systems': [{k: v for k, v in s.items() if k != '_per'} for s in results],\n",
     "}, io.open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=1, default=str)\n",
     "print('저장 →', out)"),

md("---\n",
   "\n",
   "## 정리\n",
   "\n",
   "만들어진 것\n",
   "\n",
   "- `ml/models/reranker_lora/` — 학습한 딥러닝 모델 (제출물)\n",
   "- `ml/data/reranker_results.json` — 성능 비교 결과\n",
   "- `ml/data/reranker_loss.png` — 학습 곡선 그림\n",
   "\n",
   "**결과를 어떻게 읽든 결과서는 쓸 수 있다.**\n",
   "\n",
   "| 나온 결과 | 결과서에 쓸 내용 |\n",
   "| --- | --- |\n",
   "| 학습한 쪽이 더 좋다 | 효과를 확인했다. 서비스 적용을 검토한다 |\n",
   "| 사전학습과 비슷하다 | 893쌍으로는 부족했다. 필요한 데이터 규모를 가늠했다 |\n",
   "| 오히려 나빠졌다 | 과적합. 학습 곡선으로 원인을 보인다 |\n",
   "\n",
   "실험은 좋게 나와야만 가치가 있는 게 아니다. **왜 그런지 설명할 수 있으면 된다.**"),
]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.11'},
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

out = os.path.join(HERE, '05_reranker_report.ipynb')
with io.open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('만들었다 →', out, '· 셀 %d개' % len(cells))
