# -*- coding: utf-8 -*-
"""03_ml_experiments.ipynb 를 만든다. 노트북을 손으로 고치지 말고 이 파일을 고친다."""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def md(*lines):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': list(lines)}


def code(*lines):
    return {'cell_type': 'code', 'execution_count': None, 'metadata': {},
            'outputs': [], 'source': list(lines)}


cells = [

md("# 03. 업력 분류기 — 설정을 바꿔가며 비교\n",
   "\n",
   "## 왜 하나\n",
   "\n",
   "02 번에서 업력 분류기를 **한 가지 설정으로만** 만들었다. 94% 가 나왔지만,\n",
   "**그게 좋은 건지 나쁜 건지 비교 대상이 없다.**\n",
   "\n",
   "그래서 방식을 바꿔가며 여섯 번 돌려보고 표로 만든다.\n",
   "\n",
   "| 실험 | 무엇을 바꾸나 |\n",
   "| --- | --- |\n",
   "| EXP-01 | 문장을 **단어 단위**로 자른다 (가장 단순한 기준선) |\n",
   "| EXP-02 | 문장을 **글자 2~4개**로 자른다 (02 번에서 쓴 것) |\n",
   "| EXP-03 | 개수 불균형 보정을 **끈다** |\n",
   "| EXP-04 | 선 긋는 방식을 **다른 것**으로 바꾼다 (SVM) |\n",
   "| EXP-05 | **애매하면 판단을 보류**한다 |\n",
   "| EXP-06 | **「개월/년」 구분 힌트**를 준다 (02 번에서 찾은 약점 보완) |\n",
   "\n",
   "전부 그래픽카드 없이 몇 초씩이면 끝난다.\n",
   "\n",
   "## 공정하게 비교하려면\n",
   "\n",
   "- **같은 문제집, 같은 시험지**를 쓴다. 나누는 주사위 눈금(SEED)을 고정한다.\n",
   "- 시험지는 83장뿐이라 운이 섞인다. 그래서 **교차검증**을 같이 본다 —\n",
   "  공부용 249장을 5조각으로 나눠, 4조각으로 배우고 1조각으로 시험 보기를\n",
   "  5번 돌려 평균을 낸다. 한 번 재는 것보다 흔들림이 적다."),

code("# -*- coding: utf-8 -*-\n",
     "import io, os, sys, json, re, time, collections\n",
     "\n",
     "# 어디서 띄우든 작업 폴더를 data-collection 으로 맞춘다.\n",
     "ROOT = os.getcwd()\n",
     "while not all(os.path.isdir(os.path.join(ROOT, d)) for d in ('eval', 'ml')):\n",
     "    parent = os.path.dirname(ROOT)\n",
     "    if parent == ROOT:\n",
     "        raise SystemExit('data-collection 폴더를 찾지 못했다. 저장소 안에서 실행한다.')\n",
     "    ROOT = parent\n",
     "os.chdir(ROOT)\n",
     "if ROOT not in sys.path:\n",
     "    sys.path.insert(0, ROOT)\n",
     "\n",
     "DATA = os.path.join(ROOT, 'ml', 'data')\n",
     "os.makedirs(DATA, exist_ok=True)\n",
     "print('작업 폴더 :', os.getcwd())"),

md("### 데이터 준비\n",
   "\n",
   "01 번이 만든 라벨 파일을 읽는다. 없으면 EC2 DB 에서 다시 만든다."),

code("LABELS = os.path.join(DATA, 'age_labels.jsonl')\n",
     "\n",
     "if not os.path.exists(LABELS):\n",
     "    print('라벨 파일이 없다. EC2 DB 에서 다시 만든다...')\n",
     "    import store_mysql\n",
     "    cur = store_mysql.connect().cursor()\n",
     "    cur.execute('''SELECT notice_id, age_source_quote, age_years_max,\n",
     "                          age_years_min, no_age_limit\n",
     "                     FROM notice_conditions\n",
     "                    WHERE age_source_quote IS NOT NULL AND age_source_quote <> '' ''')\n",
     "    with io.open(LABELS, 'w', encoding='utf-8') as f:\n",
     "        for nid, quote, ymax, ymin, nolimit in cur.fetchall():\n",
     "            f.write(json.dumps({\n",
     "                'notice_id': nid,\n",
     "                'quote': ' '.join(str(quote).split()),\n",
     "                'label': 1 if (ymax is not None or ymin is not None or nolimit) else 0,\n",
     "            }, ensure_ascii=False) + '\\n')\n",
     "\n",
     "rows = [json.loads(l) for l in io.open(LABELS, encoding='utf-8') if l.strip()]\n",
     "texts = [r['quote'] for r in rows]\n",
     "labels = [r['label'] for r in rows]\n",
     "print('문장 %d개 · 업력 %d · 아님 %d' % (len(rows), sum(labels), len(labels) - sum(labels)))"),

code("from sklearn.model_selection import train_test_split\n",
     "\n",
     "SEED = 20260916      # 02 번과 같은 눈금. 같은 문제집·시험지를 써야 비교가 된다\n",
     "\n",
     "X_train, X_test, y_train, y_test = train_test_split(\n",
     "    texts, labels, test_size=0.25, stratify=labels, random_state=SEED)\n",
     "\n",
     "print('공부용 %d · 시험용 %d' % (len(X_train), len(X_test)))\n",
     "print('공부용 업력 비율 %.1f%% · 시험용 %.1f%%'\n",
     "      % (sum(y_train) / len(y_train) * 100, sum(y_test) / len(y_test) * 100))"),

md("---\n",
   "\n",
   "## EXP-06 에 쓸 「단위 힌트」\n",
   "\n",
   "02 번에서 이런 약점을 찾았다 —\n",
   "\n",
   "> 학습 데이터에 **「N개월 이상」 형태 40건이 모두 「업력 아님」** 으로 들어 있어서,\n",
   "> 모델이 **「이상」 이라는 말 자체를 업력이 아닌 신호로** 잘못 배웠다.\n",
   "> 그래서 「업력이 2년 이상」 같은 진짜 업력 조건까지 놓쳤다.\n",
   "\n",
   "고치는 방법은 **모델이 헷갈리는 구분을 대신 찍어주는 것**이다.\n",
   "문장 뒤에 표시를 붙여서 「개월」과 「년」, 「이상」과 「이내」를 구별하게 한다.\n",
   "\n",
   "```\n",
   "\"3개월 이상 영업 중인 소상공인\"   →  \"3개월 이상 … __개월하한__\"\n",
   "\"업력이 2년 이상이며\"             →  \"업력이 2년 이상이며 __년하한__\"\n",
   "\"창업 후 7년 이내\"                →  \"창업 후 7년 이내 __년상한__\"\n",
   "```\n",
   "\n",
   "사람이 도메인 지식을 넣어주는 것이라 **특징 공학(feature engineering)** 이라 부른다."),

code("HINTS = [\n",
     "    (r'\\d+\\s*년\\s*(이내|미만|이하)',   '__년상한__'),\n",
     "    (r'\\d+\\s*년\\s*(이상|초과|경과)',   '__년하한__'),\n",
     "    (r'\\d+\\s*개월\\s*(이상|초과)',      '__개월하한__'),\n",
     "    (r'\\d+\\s*개월\\s*(이내|미만)',      '__개월상한__'),\n",
     "    (r'만\\s*\\d+\\s*세',                '__사람나이__'),\n",
     "    (r'(재직|근속|근무)',              '__근속__'),\n",
     "    (r'(창업|설립|개업|사업자등록)',    '__창업어휘__'),\n",
     "]\n",
     "\n",
     "def add_hints(text):\n",
     "    marks = [tag for pattern, tag in HINTS if re.search(pattern, text)]\n",
     "    return text + ' ' + ' '.join(marks) if marks else text\n",
     "\n",
     "# 붙은 표시가 라벨과 얼마나 맞물리는지 먼저 확인한다\n",
     "print('%-14s %6s %6s   %s' % ('표시', '업력', '아님', '업력 비율'))\n",
     "print('-' * 46)\n",
     "for pattern, tag in HINTS:\n",
     "    hit = [(t, l) for t, l in zip(texts, labels) if re.search(pattern, t)]\n",
     "    if hit:\n",
     "        pos = sum(l for _, l in hit)\n",
     "        print('%-14s %6d %6d   %5.1f%%' % (tag, pos, len(hit) - pos, pos / len(hit) * 100))\n",
     "\n",
     "print()\n",
     "print('예시:', add_hints('업력이 2년 이상이며 최근 6개월 매출 감소')[:70])"),

md("---\n",
   "\n",
   "## 여섯 가지 실험 정의"),

code("from sklearn.feature_extraction.text import TfidfVectorizer\n",
     "from sklearn.linear_model import LogisticRegression\n",
     "from sklearn.svm import LinearSVC\n",
     "from sklearn.pipeline import make_pipeline\n",
     "\n",
     "def word_tfidf():\n",
     "    return TfidfVectorizer(analyzer='word', ngram_range=(1, 2), min_df=2, sublinear_tf=True)\n",
     "\n",
     "def char_tfidf():\n",
     "    return TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4), min_df=2, sublinear_tf=True)\n",
     "\n",
     "def lr(balanced=True):\n",
     "    return LogisticRegression(max_iter=2000, C=1.0,\n",
     "                              class_weight='balanced' if balanced else None)\n",
     "\n",
     "EXPERIMENTS = [\n",
     "    ('EXP-01', '단어 단위 + 로지스틱 회귀 (기준선)',\n",
     "     lambda: make_pipeline(word_tfidf(), lr()), None, None),\n",
     "    ('EXP-02', '글자 2~4개 + 로지스틱 회귀 (02번에서 쓴 것)',\n",
     "     lambda: make_pipeline(char_tfidf(), lr()), None, None),\n",
     "    ('EXP-03', '글자 2~4개 + 불균형 보정 끔',\n",
     "     lambda: make_pipeline(char_tfidf(), lr(balanced=False)), None, None),\n",
     "    ('EXP-04', '글자 2~4개 + 선형 SVM',\n",
     "     lambda: make_pipeline(char_tfidf(), LinearSVC(class_weight='balanced')), None, None),\n",
     "    ('EXP-05', 'EXP-02 + 애매하면 판단 보류 (0.35~0.65)',\n",
     "     lambda: make_pipeline(char_tfidf(), lr()), (0.35, 0.65), None),\n",
     "    ('EXP-06', 'EXP-02 + 개월/년 단위 힌트',\n",
     "     lambda: make_pipeline(char_tfidf(), lr()), None, add_hints),\n",
     "]\n",
     "\n",
     "print('실험 %d개' % len(EXPERIMENTS))\n",
     "for name, desc, _, abstain, prep in [(e[0], e[1], None, e[2], e[3]) for e in EXPERIMENTS]:\n",
     "    print('  %s  %s' % (name, desc))"),

md("---\n",
   "\n",
   "## 실행\n",
   "\n",
   "**지표 읽는 법** (업력이라고 판단한 것 기준)\n",
   "\n",
   "| 이름 | 뜻 | 낮으면 |\n",
   "| --- | --- | --- |\n",
   "| 정밀도 | 업력이라 한 것 중 진짜 업력 비율 | 엉뚱한 걸 업력으로 읽어 **잘못된 자격 판정** |\n",
   "| 재현율 | 진짜 업력 중 찾아낸 비율 | 업력을 놓쳐서 **판정을 못 함** |\n",
   "| F1 | 둘의 균형 | |\n",
   "| 적용률 | 판단을 내린 비율 (보류 제외) | 보류가 많으면 낮아진다 |\n",
   "\n",
   "이 프로젝트에서는 **정밀도가 더 중요하다.** 놓치면 「확인 필요」로 남기면 되지만,\n",
   "잘못 읽으면 사용자에게 틀린 자격 판정을 보여주게 된다."),

code("from sklearn.model_selection import StratifiedKFold\n",
     "from sklearn.metrics import precision_recall_fscore_support, accuracy_score\n",
     "import numpy as np\n",
     "\n",
     "def scores(truth, pred):\n",
     "    p, r, f, _ = precision_recall_fscore_support(\n",
     "        truth, pred, labels=[1], zero_division=0, average='binary')\n",
     "    return accuracy_score(truth, pred), p, r, f\n",
     "\n",
     "def run_one(build, abstain, prep):\n",
     "    tr = [prep(t) for t in X_train] if prep else X_train\n",
     "    te = [prep(t) for t in X_test] if prep else X_test\n",
     "\n",
     "    # ① 교차검증 — 공부용 249장을 5조각으로 나눠 5번 재고 평균\n",
     "    cv_f1 = []\n",
     "    kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)\n",
     "    tr_arr, y_arr = np.array(tr, dtype=object), np.array(y_train)\n",
     "    for fit_idx, val_idx in kf.split(tr_arr, y_arr):\n",
     "        m = build()\n",
     "        m.fit(list(tr_arr[fit_idx]), list(y_arr[fit_idx]))\n",
     "        _, _, _, f = scores(list(y_arr[val_idx]), m.predict(list(tr_arr[val_idx])))\n",
     "        cv_f1.append(f)\n",
     "\n",
     "    # ② 시험지 83장\n",
     "    t0 = time.time()\n",
     "    model = build()\n",
     "    model.fit(tr, y_train)\n",
     "    fit_sec = time.time() - t0\n",
     "\n",
     "    truth, pred = list(y_test), list(model.predict(te))\n",
     "    coverage = 1.0\n",
     "    if abstain and hasattr(model, 'predict_proba'):\n",
     "        low, high = abstain\n",
     "        proba = model.predict_proba(te)[:, 1]\n",
     "        keep = [i for i, p in enumerate(proba) if not (low <= p <= high)]\n",
     "        coverage = len(keep) / len(te)\n",
     "        truth = [y_test[i] for i in keep]\n",
     "        pred = [1 if proba[i] > high else 0 for i in keep]\n",
     "\n",
     "    acc, p, r, f1 = scores(truth, pred)\n",
     "    return {'cv_f1_mean': float(np.mean(cv_f1)), 'cv_f1_std': float(np.std(cv_f1)),\n",
     "            'accuracy': acc, 'precision': p, 'recall': r, 'f1': f1,\n",
     "            'coverage': coverage, 'fit_sec': fit_sec, 'model': model}\n",
     "\n",
     "results = []\n",
     "for name, desc, build, abstain, prep in EXPERIMENTS:\n",
     "    out = run_one(build, abstain, prep)\n",
     "    out.update({'exp': name, 'desc': desc})\n",
     "    results.append(out)\n",
     "    print('%s  F1 %.3f (CV %.3f±%.3f) · 정밀도 %.3f · 재현율 %.3f · 적용률 %.0f%% · %.1f초'\n",
     "          % (name, out['f1'], out['cv_f1_mean'], out['cv_f1_std'],\n",
     "             out['precision'], out['recall'], out['coverage'] * 100, out['fit_sec']))"),

md("---\n",
   "\n",
   "## 결과표\n",
   "\n",
   "**「학습 결과서」 3.2 실험 결과 비교 표에 그대로 들어갈 내용이다.**"),

code("# 고르는 기준을 먼저 정해두고 그대로 따른다 (결과를 보고 기준을 바꾸지 않는다).\n",
     "#   후보  : 적용률 100% 인 것만. 보류를 쓰는 EXP-05 는 판단 건수가 달라 나란히 못 둔다\n",
     "#   1순위 : 정밀도 — 이 프로젝트는 「잘못 말하지 않는 것」이 「많이 말하는 것」보다 중요하다\n",
     "#   동률  : F1\n",
     "full = [r for r in results if r['coverage'] >= 0.999]\n",
     "best = max(full, key=lambda r: (round(r['precision'], 3), r['f1']))\n",
     "\n",
     "print('%-8s %-34s %-8s %-14s %-8s %-8s %-7s'\n",
     "      % ('실험', '설정', 'F1', '교차검증 F1', '정밀도', '재현율', '적용률'))\n",
     "print('-' * 96)\n",
     "for r in results:\n",
     "    mark = ' ← 선택' if r is best else ''\n",
     "    print('%-8s %-34s %-8.3f %-14s %-8.3f %-8.3f %-6.0f%%%s'\n",
     "          % (r['exp'], r['desc'][:33], r['f1'],\n",
     "             '%.3f±%.3f' % (r['cv_f1_mean'], r['cv_f1_std']),\n",
     "             r['precision'], r['recall'], r['coverage'] * 100, mark))\n",
     "print()\n",
     "print('선택 : %s — %s' % (best['exp'], best['desc']))\n",
     "print('       (적용률 100%% 중 정밀도 최고: %.3f)' % best['precision'])\n",
     "print()\n",
     "print('※ EXP-05 는 F1 이 가장 높아 보이지만 **판단을 절반만** 한다(적용률 54%).')\n",
     "print('   전부 판단한 것과 나란히 비교할 수 없다. 서비스에 켜고 끄는 선택지로 따로 본다.')"),

md("### ⚠ 교차검증과 시험지가 다른 말을 한다\n",
   "\n",
   "표를 보면 두 숫자의 순위가 어긋난다. 이건 **데이터가 적다는 신호**다.\n",
   "\n",
   "```\n",
   "교차검증 F1 (249장을 5번 나눠 잼)   EXP-01 이 가장 높다\n",
   "시험지 F1  (83장 한 번 잼)          EXP-02 가 가장 높다\n",
   "```\n",
   "\n",
   "시험지가 83장뿐이라 **한 번 재면 운이 섞인다.** 교차검증의 ±(0.02~0.08)보다\n",
   "작은 차이는 우연으로 봐야 한다.\n",
   "\n",
   "**확실하게 말할 수 있는 것은 두 가지뿐이다.**\n",
   "\n",
   "- EXP-03(불균형 보정 끔)은 **재현율이 뚜렷하게 낮다** — 보정은 켜는 게 맞다\n",
   "- 나머지 차이는 흔들림 범위 안이라 **순위를 단정할 수 없다**\n",
   "\n",
   "이럴 때는 숫자 하나로 고르지 말고 **미리 정한 기준**(정밀도 우선)을 따르는 것이 맞다."),

md("### EXP-02 와 EXP-06 비교 — 약점이 고쳐졌나\n",
   "\n",
   "02 번에서 찾은 문제는 **「N년 이상」 형태를 업력이 아니라고 판단하는 것**이었다.\n",
   "힌트를 준 EXP-06 이 그 부분에서 실제로 나아졌는지 따로 확인한다."),

code("target = re.compile(r'\\d+\\s*년\\s*(이상|초과|경과)')\n",
     "idx = [i for i, t in enumerate(X_test) if target.search(t)]\n",
     "\n",
     "if not idx:\n",
     "    print('시험지에 「N년 이상」 문장이 없다.')\n",
     "else:\n",
     "    print('시험지 중 「N년 이상」 이 들어간 문장 %d개' % len(idx))\n",
     "    print()\n",
     "    for exp in ('EXP-02', 'EXP-06'):\n",
     "        r = next(x for x in results if x['exp'] == exp)\n",
     "        prep = add_hints if exp == 'EXP-06' else None\n",
     "        te = [prep(X_test[i]) for i in idx] if prep else [X_test[i] for i in idx]\n",
     "        pred = r['model'].predict(te)\n",
     "        truth = [y_test[i] for i in idx]\n",
     "        ok = sum(1 for a, b in zip(truth, pred) if a == b)\n",
     "        print('%s  %d/%d 맞음 (%.0f%%)' % (exp, ok, len(idx), ok / len(idx) * 100))\n",
     "    print()\n",
     "    r2 = next(x for x in results if x['exp'] == 'EXP-02')\n",
     "    r6 = next(x for x in results if x['exp'] == 'EXP-06')\n",
     "    for i in idx:\n",
     "        p2 = r2['model'].predict([X_test[i]])[0]\n",
     "        p6 = r6['model'].predict([add_hints(X_test[i])])[0]\n",
     "        if p2 != p6:\n",
     "            mark = lambda v: '업력' if v else '아님'\n",
     "            print('정답 %s · EXP-02 %s · EXP-06 %s'\n",
     "                  % (mark(y_test[i]), mark(p2), mark(p6)))\n",
     "            print('   ', X_test[i][:70])"),

md("---\n",
   "\n",
   "## 그림 — 실험별 성능"),

code("import matplotlib\n",
     "matplotlib.rcParams['font.family'] = 'Malgun Gothic'\n",
     "matplotlib.rcParams['axes.unicode_minus'] = False\n",
     "import matplotlib.pyplot as plt\n",
     "\n",
     "names = [r['exp'] for r in results]\n",
     "x = np.arange(len(names))\n",
     "fig, ax = plt.subplots(figsize=(8, 3.8))\n",
     "ax.bar(x - 0.22, [r['precision'] for r in results], 0.2, label='정밀도')\n",
     "ax.bar(x, [r['recall'] for r in results], 0.2, label='재현율')\n",
     "ax.bar(x + 0.22, [r['f1'] for r in results], 0.2, label='F1')\n",
     "ax.errorbar(x, [r['cv_f1_mean'] for r in results],\n",
     "            yerr=[r['cv_f1_std'] for r in results],\n",
     "            fmt='o', color='black', markersize=4, capsize=3, label='교차검증 F1')\n",
     "ax.set_xticks(x); ax.set_xticklabels(names)\n",
     "ax.set_ylim(0, 1.05); ax.grid(axis='y', alpha=.3)\n",
     "ax.legend(ncol=4, fontsize=8, loc='lower right')\n",
     "ax.set_title('업력 분류기 실험 비교')\n",
     "fig.tight_layout()\n",
     "fig.savefig(os.path.join(DATA, 'ml_experiments.png'), dpi=150)\n",
     "plt.show()"),

md("---\n",
   "\n",
   "## 최종 모델 저장\n",
   "\n",
   "F1 이 가장 높은 설정으로 **전체 332개를 다 써서** 다시 학습해 저장한다.\n",
   "비교는 끝났으니 이제 데이터를 아낄 이유가 없다."),

code("import joblib\n",
     "\n",
     "MODELS = os.path.join(ROOT, 'ml', 'models')\n",
     "os.makedirs(MODELS, exist_ok=True)\n",
     "\n",
     "chosen = next(e for e in EXPERIMENTS if e[0] == best['exp'])\n",
     "_, desc, build, abstain, prep = chosen\n",
     "final = build()\n",
     "final.fit([prep(t) for t in texts] if prep else texts, labels)\n",
     "\n",
     "path = os.path.join(MODELS, 'age_classifier_v2.joblib')\n",
     "joblib.dump({'model': final, 'uses_hints': prep is not None,\n",
     "             'abstain': abstain, 'exp': best['exp'], 'seed': SEED}, path)\n",
     "print('저장 → %s (%.1f KB)' % (path, os.path.getsize(path) / 1024))\n",
     "print('선택된 설정 : %s — %s' % (best['exp'], desc))\n",
     "\n",
     "for s in ['창업 후 5년 이내 중소기업', '업력이 2년 이상인 기업',\n",
     "          '장기재직 3년 이상 근로자', '6개월 이상 영업 중인 소상공인']:\n",
     "    q = prep(s) if prep else s\n",
     "    p = final.predict_proba([q])[0][1] if hasattr(final, 'predict_proba') else float(final.predict([q])[0])\n",
     "    print('  %-28s → 업력일 확률 %.0f%%' % (s, p * 100))"),

code("out = os.path.join(DATA, 'ml_experiments.json')\n",
     "json.dump({\n",
     "    'seed': SEED, 'n_total': len(rows), 'n_train': len(X_train), 'n_test': len(X_test),\n",
     "    'chosen': best['exp'],\n",
     "    'experiments': [{k: v for k, v in r.items() if k != 'model'} for r in results],\n",
     "}, io.open(out, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)\n",
     "print('저장 →', out)"),

md("---\n",
   "\n",
   "## 정리\n",
   "\n",
   "만들어진 것\n",
   "\n",
   "- `ml/models/age_classifier_v2.joblib` — 비교 끝에 고른 최종 모델\n",
   "- `ml/data/ml_experiments.json` — 실험 결과 (문서에 넣을 표)\n",
   "- `ml/data/ml_experiments.png` — 비교 그림\n",
   "\n",
   "**결과를 어떻게 읽든 결과서에 쓸 수 있다.**\n",
   "\n",
   "| 나온 결과 | 쓸 내용 |\n",
   "| --- | --- |\n",
   "| EXP-06 이 가장 좋다 | 오류 분석으로 약점을 찾아 특징 공학으로 해결했다 |\n",
   "| EXP-02 와 비슷하다 | 힌트가 도움이 되지 않았다. 데이터가 이미 그 정보를 담고 있었다 |\n",
   "| 오히려 나빠졌다 | 힌트가 잡음이 되었다. 규칙을 손으로 넣는 것의 한계 |\n",
   "\n",
   "교차검증의 ± 보다 작은 차이는 **우연일 수 있다.** 그 점을 같이 적는다."),
]

nb = {
    'cells': cells,
    'metadata': {
        'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
        'language_info': {'name': 'python', 'version': '3.11'},
    },
    'nbformat': 4,
    'nbformat_minor': 5,
}

out = os.path.join(HERE, '03_ml_experiments.ipynb')
with io.open(out, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('만들었다 →', out, '· 셀 %d개' % len(cells))
